### ISSUE TITLE
Exciting problem.

### ISSUE THREAD

**Issue by yasNing** [WJoyZheng/HypHKGE#1]
Hi, Wenjie: 

I guess this work provide a novel perspective of the hierarchy modeling in Hyperbolic KG. Your work clearly identify the problem, and inroduce the inter-level  transformations (by a k-times transformations In tangent space) to sovle your problem. I'm interested in your work. So which conference did you submit this paper to?

**Comment by wjzhengnlp** [comment]
hi, we have submitted the paper to TNNLS.
